name: CI/CD Pipeline for Node App

on:
  push:
    branches:
      - main  # or 'master', based on your repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Match your local version

      - name: Install Dependencies
        run: npm install

      - name: Run Lint (Optional)
        run: echo "Linting skipped"  # Add ESLint here if needed

      - name: Run Tests
        run: echo "No tests defined"

      - name: Build Docker Image
        run: docker build -t simple-node-app .

      # Optional: Push to DockerHub or deploy to a server
